import About from "@/components/About";
import Main from "@/components/Main";
import Navbar from "@/components/Navbar";
import Projects from "@/components/Projects";
import Skills from "@/components/Skills";
import Head from "next/head";
import Script from "next/script";
import * as React from 'react';

export default function Home() {
  return (
      <div>
        <Head>
          <title>Kojaydev | Software Engineer</title>
          <meta name="author" content="@Kojaydev"></meta>
          <meta name="description" content="Generated by Next App"></meta>
          <link rel="icon" href="/favicon.ico"></link>
          <link href="https://unpkg.com/aos@2.3.1/dist/aos.css" rel="stylesheet"></link>
        </Head>
        <Navbar />
        <Main />
        <About />
        <Skills />
        <Projects />

        <Script src="https://unpkg.com/aos@2.3.1/dist/aos.js"/>
        <Script src="/script.js"/>
      </div>
  )
}
