import About from "@/components/About";
import Main from "@/components/Main";
import Navbar from "@/components/Navbar";
import Projects from "@/components/Projects";
import Skills from "@/components/Skills";
import Head from "next/head";


export default function Home() {
  return (
      <div>
        <Head>
          <title>Kojaydev | Software Engineer</title>
          <meta name="author" content="@Kojaydev"></meta>
          <meta name="description" content="Generated by Next App"></meta>
          <link rel="icon" href="/favicon.ico"></link>
        </Head>
        <Navbar />
        <Main />
        <About />
        <Skills />
        <Projects />
      </div>
  )
}
